export const APP_NAME = "Arc Forge AI"
export const APP_MARK = "AF"
export const AI_ASSISTANT_NAME = "Arc Forge Architect"
export const AI_WORKSPACE_TITLE = "AI Workspace"
export const AI_WORKSPACE_TAGLINE = "Design and document systems with Arc Forge AI"
